# Usamos uma imagem base mais completa e confiável
image: gitpod/workspace-full

tasks:
  - init: |
      echo "Iniciando setup robusto com pyenv..."
      # Instala as dependências necessárias para compilar o Python
      sudo apt-get update -y
      sudo apt-get install -y make build-essential libssl-dev zlib1g-dev       libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm       libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev

      # Instala o pyenv
      curl https://pyenv.run | bash

      # Configura o shell para usar o pyenv
      echo 'export PYENV_ROOT="/home/vscode/.pyenv"' >> ~/.bashrc
      echo 'export PATH="/bin:/usr/local/gitpod/shared/vscode/vscode-server/bin/7d842fb85a0275a4a8e4d7e040d2625abbf7f084/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/vscode/.local/bin"' >> ~/.bashrc
      echo 'eval ""' >> ~/.bashrc
      # Aplica as mudanças no shell atual
      export PYENV_ROOT="/home/vscode/.pyenv"
      export PATH="/bin:/usr/local/gitpod/shared/vscode/vscode-server/bin/7d842fb85a0275a4a8e4d7e040d2625abbf7f084/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/vscode/.local/bin"
      eval ""

      # Instala a versão 3.11.8 do Python (pode levar alguns minutos)
      echo "Instalando Python 3.11.8... Isso pode levar de 2 a 3 minutos."
      pyenv install 3.11.8
      
      # Define a versão 3.11.8 como padrão global
      pyenv global 3.11.8
      
      echo "Python instalado e configurado!"
      python --version

      # Continua com nosso setup original
      echo "Criando ambiente virtual..."
      python -m venv .venv
      
      echo "Instalando dependências do projeto..."
      source .venv/bin/activate && pip install -r requirements.txt
      
      echo "Setup completo e à prova de falhas!"
    before: |
      # Garante que o pyenv e o venv estejam ativos nos terminais subsequentes
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init --path)"
      if [ -f .venv/bin/activate ]; then source .venv/bin/activate; fi

ports:
  - port: 8080
    onOpen: open-browser
